type: BIGCONFIG_FILE
tag_deployments:
- collection:
    name: Operational Checks
    notification_channels:
    - slack: '#de-bigeye-triage'
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_firefox_derived.baseline_clients_last_seen_v1.submission_date
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_firefox_derived.baseline_clients_last_seen_v1.client_id
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_firefox_derived.baseline_clients_last_seen_v1.sample_id
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_firefox_derived.baseline_clients_last_seen_v1.days_seen_bits
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_firefox_derived.baseline_clients_last_seen_v1.days_active_bits
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_firefox_derived.baseline_clients_last_seen_v1.days_created_profile_bits
    metrics:
    - saved_metric_id: is_not_null
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_firefox_derived.baseline_clients_last_seen_v1.first_seen_date
    metrics:
    - saved_metric_id: is_99_percent_not_null
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_firefox_derived.baseline_clients_last_seen_v1.normalized_channel
    metrics:
    - saved_metric_id: is_99_percent_valid_normalized_channel
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_firefox_derived.baseline_clients_last_seen_v1.*
    metrics:
    - saved_metric_id: freshness
    - saved_metric_id: volume
