type: BIGCONFIG_FILE
tag_deployments:
- collection:
    name: Operational Checks
    notification_channels:
    - slack: '#de-bigeye-triage'
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefox_ios_derived.retention_v1.first_seen_date
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefox_ios_derived.retention_v1.app_name
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefox_ios_derived.retention_v1.is_mobile
    metrics:
    - saved_metric_id: is_not_null
      lookback:
        lookback_window:
          interval_type: DAYS
          interval_value: 28
        lookback_type: DATA_TIME
      rct_overrides:
      - metric_date
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefox_ios_derived.retention_v1.normalized_channel
    metrics:
    - saved_metric_id: is_99_percent_valid_normalized_channel
      lookback:
        lookback_window:
          interval_type: DAYS
          interval_value: 28
        lookback_type: DATA_TIME
      rct_overrides:
      - metric_date
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefox_ios_derived.retention_v1.*
    metrics:
    - saved_metric_id: volume
    - saved_metric_id: freshness
