type: BIGCONFIG_FILE
tag_deployments:
  - collection:
    notification_channels:
    - slack: '#de-bigeye-triage'
table_deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.{{ app_name }}_derived.active_users_aggregates_v3.*
    metrics:
    - metric_type:
        type: PREDEFINED
        predefined_metric: FRESHNESS
      metric_name: FRESHNESS
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
    - metric_type:
        type: PREDEFINED
        predefined_metric: VOLUME
      metric_name: VOLUME
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
