friendly_name: Firefox-CI Tasks
description: |-
  Derived Firefox-CI task data exported from Taskcluster pulse.
owners:
- ahalberstadt@mozilla.com
labels:
  owner1: ahalberstadt
workgroup_access:
- role: roles/bigquery.dataViewer
  members:
  - workgroup:mozilla-confidential/data-viewers
references:
  view.sql:
  - moz-fx-data-shared-prod.fxci_derived.tasks_v2
