friendly_name: Tasks
description: |-
  Please provide a description for the query
owners: []
labels: {}
bigquery: null
workgroup_access:
- role: roles/bigquery.dataViewer
  members:
  - workgroup:mozilla-confidential
references:
  view.sql:
  - moz-fx-data-shared-prod.fxci_derived.tasks_v2
require_column_descriptions: false
