type: BIGCONFIG_FILE
tag_deployments:
- collection:
    name: Operational Checks
    notification_channels:
    - slack: '#de-bigeye-triage'
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefox_desktop_derived.baseline_clients_daily_v1.submission_date
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefox_desktop_derived.baseline_clients_daily_v1.client_id
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefox_desktop_derived.baseline_clients_daily_v1.sample_id
    metrics:
    - saved_metric_id: is_not_null
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefox_desktop_derived.baseline_clients_daily_v1.first_seen_date
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefox_desktop_derived.baseline_clients_daily_v1.first_run_date
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefox_desktop_derived.baseline_clients_daily_v1.durations
    metrics:
    - saved_metric_id: is_99_percent_not_null
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefox_desktop_derived.baseline_clients_daily_v1.normalized_channel
    metrics:
    - saved_metric_id: is_99_percent_valid_normalized_channel
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.firefox_desktop_derived.baseline_clients_daily_v1.*
    metrics:
    - saved_metric_id: freshness
    - saved_metric_id: volume
