---
addcode_topsite:
  name: "addcode_topsite"
  description: ""
  start_date: "2020-03-14"
  end_date: "2021-07-31"
  prior_scale: 1
  mode: "multiplicative"

post_esr_migration:
  name: "post_esr_migration"
  description: "Dates following migration of clients on old OS versions from release to ESR"
  start_date: "2023-07-29"
  prior_scale: 1
  mode: "additive"

after_fenix:
  name: "after_fenix"
  description: "Dates following migration of fenix clients"
  start_date: "2020-08-15"
  prior_scale: 1
  mode: "additive"

in_covid:
  name: "in_covid"
  description: "Period that covers early impact of Covid"
  start_date: "2020-03-14"
  end_date: "2021-07-31"
  prior_scale: 1
  mode: "additive"

ad_click_bug:
  name: "ad_click_bug"
  description: "Period after known bug surfaced regarding ad clicks"
  start_date: "2023-07-01"
  mode: "multiplicative"
