---
metric_hub:
  app_name: "multi_product"
  slug: "mobile_daily_active_users_v1"
  alias: "mobile_dau"
  start_date: "2021-02-01"
  end_date: NULL

forecast_model:
  model_type: "prophet"
  start_date: NULL
  end_date: NULL
  use_holidays: True
  parameters:
    seasonality_prior_scale: 0.01
    changepoint_prior_scale: 0.01
    weekly_seasonality: True
    yearly_seasonality: True

summarize:
  periods: ["day", "month"]
  numpy_aggregations: ["mean"]
  percentiles: [5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95]

write_results:
  project: "moz-fx-data-shared-prod"
  project_legacy: "moz-fx-data-shared-prod"
  dataset: "telemetry_derived"
  dataset_legacy: "telemetry_derived"
  table: "kpi_forecasts_v0"
