---
metric_hub:
  app_name: "firefox_desktop"
  slug: "daily_active_users_v2"
  alias: "desktop_dau"
  start_date: "2018-01-01"
  end_date: NULL

forecast_model:
  model_type: "prophet"
  start_date: NULL
  end_date: NULL
  use_holidays: False
  parameters:
    seasonality_prior_scale: 0.00825
    changepoint_prior_scale: 0.15983
    weekly_seasonality: True
    yearly_seasonality: True

summarize:
  periods: ["day", "month"]
  numpy_aggregations: ["mean"]
  percentiles: [5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95]

write_results:
  project: "moz-fx-data-shared-prod"
  project_legacy: "moz-fx-data-shared-prod"
  dataset: "telemetry_derived"
  dataset_legacy: "telemetry_derived"
  table: "kpi_forecasts_v0"
