type: BIGCONFIG_FILE
tag_deployments:
- collection:
    name: Browser Metrics (non-KPI)
    notification_channels:
    - slack: '#ds-bigeye-triage'
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.klar_ios_derived.engagement_v1.first_seen_date
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.klar_ios_derived.engagement_v1.app_name
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.klar_ios_derived.engagement_v1.normalized_channel
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.klar_ios_derived.engagement_v1.is_mobile
    metrics:
    - saved_metric_id: is_not_null
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.klar_ios_derived.engagement_v1.normalized_channel
    metrics:
    - saved_metric_id: is_valid_channel
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.klar_ios_derived.engagement_v1.country
    metrics:
    - saved_metric_id: is_2_char_len
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.klar_ios_derived.engagement_v1.*
    metrics:
    - saved_metric_id: volume
    - saved_metric_id: freshness
- collection:
    name: Operational Checks
    notification_channels:
    - slack: '#de-bigeye-triage'
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.klar_ios_derived.engagement_v1.*
    metrics:
    - saved_metric_id: freshness
    - saved_metric_id: volume
- collection:
    name: Browser Metrics (non-KPI)
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.klar_ios_derived.engagement_v1.*
    metrics:
    - metric_type:
        type: PREDEFINED
        predefined_metric: FRESHNESS
      metric_name: FRESHNESS [warn]
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
    - metric_type:
        type: PREDEFINED
        predefined_metric: VOLUME
      metric_name: VOLUME [fail]
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
