---
# Generated via bigquery_etl.glean_usage

type: BIGCONFIG_FILE

tag_deployments:
  - collection:
      name: Operational Checks
      notification_channels:
        - slack: '#de-bigeye-triage'
    deployments:
      - column_selectors:
          - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_fenix_nightly_derived.baseline_clients_first_seen_v1.client_id
        metrics:
          - saved_metric_id: is_unique
      - column_selectors:
          - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_fenix_nightly_derived.baseline_clients_first_seen_v1.submission_date
          - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_fenix_nightly_derived.baseline_clients_first_seen_v1.client_id
          - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_fenix_nightly_derived.baseline_clients_first_seen_v1.sample_id
          - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_fenix_nightly_derived.baseline_clients_first_seen_v1.first_seen_date
        metrics:
          - saved_metric_id: is_not_null
      - column_selectors:
        - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_fenix_nightly_derived.baseline_clients_first_seen_v1.*
        metrics:
          - saved_metric_id: freshness
          - saved_metric_id: volume
