type: BIGCONFIG_FILE

tag_deployments:
  - collection:
      name: Operational Checks
      notification_channels:
        - slack: '#de-bigeye-triage'
    deployments:
      - column_selectors:
          - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.android_app_campaign_stats_v1.date
          - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.android_app_campaign_stats_v1.campaign_region
          - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.android_app_campaign_stats_v1.campaign_country_code
          - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.android_app_campaign_stats_v1.campaign_language
          - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.android_app_campaign_stats_v1.ad_group
          # For now commented out due to attribution being disabled.
          # - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.android_app_campaign_stats_v1.impressions
          # - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.android_app_campaign_stats_v1.clicks
          # - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.android_app_campaign_stats_v1.new_profiles
          # - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.android_app_campaign_stats_v1.activated_profiles
          # - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.android_app_campaign_stats_v1.repeat_users
          # - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.android_app_campaign_stats_v1.week_4_retained_users
          # - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.android_app_campaign_stats_v1.spend
          # - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.android_app_campaign_stats_v1.lifetime_value
        metrics:
          - saved_metric_id: is_not_null
            lookback:
              lookback_type: DATA_TIME
              lookback_window:
                interval_type: DAYS
                interval_value: 28
            rct_overrides:
              - date
      - column_selectors:
          - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.android_app_campaign_stats_v1.campaign_country_code
        metrics:
          - saved_metric_id: is_2_char_len
            lookback:
              lookback_type: DATA_TIME
              lookback_window:
                interval_type: DAYS
                interval_value: 28
            rct_overrides:
              - date
      - column_selectors:
          - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.android_app_campaign_stats_v1.*
        metrics:
          - saved_metric_id: volume
            lookback:
              lookback_type: DATA_TIME
              lookback_window:
                interval_type: DAYS
                interval_value: 28
            rct_overrides:
              - date
          - saved_metric_id: freshness
            lookback:
              lookback_type: DATA_TIME
              lookback_window:
                interval_type: DAYS
                interval_value: 28
            rct_overrides:
              - date
