type: BIGCONFIG_FILE
tag_deployments:
- collection:
    notification_channels:
    - slack: '#ds-bigeye-triage'
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.telemetry.active_users_aggregates
    metrics:
    - metric_type:
        type: PREDEFINED
        predefined_metric: FRESHNESS
      metric_name: FRESHNESS
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
    - metric_type:
        type: PREDEFINED
        predefined_metric: VOLUME
      metric_name: VOLUME [fail]
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
